services:
  app:
    build:
      context: .
    ports:
      - '3000:3000' 
    environment:
      DATABASE_URL: "postgres://default:ZDQ7EjAIXY0U@ep-flat-morning-a1efwc0r.ap-southeast-1.aws.neon.tech:5432/verceldb?sslmode=require"

  prisma:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      DATABASE_URL: postgres://default:ZDQ7EjAIXY0U@ep-flat-morning-a1efwc0r.ap-southeast-1.aws.neon.tech:5432/verceldb?sslmode=require"
    command: npx prisma studio
    ports:
      - '5555:5555' 
