name: Docker CI/CD

on:
  push:
    branches:
      - main 

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      
      - name: Check out the repository
        uses: actions/checkout@v3

      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -name: Create .env file
        run: |
          echo "NODE_ENV=production">>.env
          echo "DATABASE_URL=${{secrets.DATABASE_URL}}" >> .env
          echo "NEXTAUTH_SECRET=${{secrets.NEXTAUTH_SECRET}}" >> .env

      
      - name: Build the Docker image
        run: |
          docker build -t pisitauu/numer:latest .

    
      - name: Push the Docker image
        run: |
          docker push pisitauu/numer:latest
